#!/usr/bin/env bash
# Concatenate the capture pipeline into one DevTools-pasteable snippet.
# The capture files are extension/DevTools dual-mode by design, so this is a
# plain cat in load order — no build toolchain.
#
# Usage: tools/make-snippet.sh   (writes snippet/deel-quick-snippet.js)
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=snippet/deel-quick-snippet.js
mkdir -p snippet

{
  echo "/* Deel Quick — DevTools snippet build. Generated by tools/make-snippet.sh — do not edit by hand."
  echo "   Paste into DevTools Console (or Sources > Snippets) on a logged-in Deel page, then run:"
  echo "   __deelQuick.run({ intent: 'what to improve', delayMs: 0, downscaleImages: false }) */"
  cat extension/capture/util.js
  cat extension/capture/dom-snapshot.js
  cat extension/capture/css-inline.js
  cat extension/capture/assets.js
  cat extension/capture/main.js
  echo "console.log('[deel-quick] loaded — run __deelQuick.run({intent: \"...\"}) to capture this page');"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
